### ISSUE TITLE
Slave failing to create containerizer

### ISSUE THREAD

**Issue by mymac80** [mesosphere/docker-containers#17]
```
docker run --net=host --privileged=true -p 5051:5051 \
-e MESOS_LOG_DIR=/var/log/mesos \
-e MESOS_MASTER=zk://<master-ip>:2181/mesos \
-e MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins \
-e MESOS_HOSTNAME=<slave-ip> \
-e MESOS_ISOLATOR=cgroups/cpu,cgroups/mem \
-e MESOS_CONTAINERIZERS=docker,mesos \
-e MESOS_PORT=5051 \
-e MESOS_IP=<slave-ip> \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /cgroup:/cgroup \
-v /sys:/sys \
-v /proc:/proc \
-v /usr/bin/docker:/usr/bin/docker \
-t mesosphere/mesos-slave:0.22.0-1.0.ubuntu1404
```
Here is the output on CentOS 7 & docker version 1.6.0:

```
I0614 05:20:06.284247     1 logging.cpp:172] INFO level logging started!
I0614 05:20:06.284539     1 main.cpp:156] Build: 2015-03-26 13:35:27 by root
I0614 05:20:06.284554     1 main.cpp:158] Version: 0.22.0
I0614 05:20:06.284560     1 main.cpp:161] Git tag: 0.22.0
I0614 05:20:06.284566     1 main.cpp:165] Git SHA: e890e2414903bb69cab730d5204f10b10d2e91bb
Failed to create a containerizer: Could not create DockerContainerizer: Failed to execute 'docker version': exited with status 127
```
Slave works fine without `-e MESOS_CONTAINERIZERS=docker,mesos`

**Comment by cmaloney** [comment]
Running mesos-slave in a docker isn't a particularly recommended operation (Esp. for production), a lot of mesos bits currently program in logic manually manipulating cgroups that can break in subtle ways.

As far as why the docker containerizer isn't working in your case, do you have installed and the daemon running on the host system? That command is mounting in docker from the host system and using it for launching mesos tasks.

**Comment by upccup** [comment]
I have the same problem. and  event  without -e MESOS_CONTAINERIZERS=docker,mesos  it also have this problem .we run docker 1.7 in centos 7

**Comment by upccup** [comment]
@mymac80  Have you solved the problem?   now i have the same problem,  and i have no way not to resolve

**Comment by tnachen** [comment]
@mymac80 it doesn't work because you don't have docker installed in your docker container, since you're just using the mesos image it doens't have docker client installed.
You should create a new image based on your mesos image but also have the docker client installed

**Comment by mymac80** [comment]
@tnachen Thanks! Will give this a try.

**Comment by PhroZenOne** [comment]
@tnachen using --privileged and   -v /var/run/docker.sock:/run/docker.sock  -v $(which docker):/bin/docker

**Comment by cengizIO** [comment]
Hello.

I'm bumping into same issue using `mesosphere/mesos-slave:0.28.1` with `docker 1.11.1` on `4.5.4-1-ARCH` kernel.

Problem seems to be `libsystemd.so.0` when I type `docker` inside container image.

```
root@b127c72e50a5:/# docker
docker: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory
```

Trusting the `cat /etc/issue` output, `mesosphere/mesos-slave:0.28.1` seems to be based on `Ubuntu 14.04.4 LTS`

Here are the missing links for `docker` binary **which I mounted from my host into /bin of container** 

```
root@b127c72e50a5:/# ldd /bin/docker
	linux-vdso.so.1 =>  (0x00007ffce3935000)
	libsystemd.so.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f514bf6e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f514bd69000)
	libdevmapper.so.1.02 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f514b9a4000)
	/lib64/ld-linux-x86-64.so.2 (0x000055bd1ddee000)
```

Maybe this will help a bit

Thanks

**Comment by itstarting** [comment]
While running docker-in-docker, it's required to mount some missing libs from host to container if you don't want to install them explicitly into the container.

For example, below works for me while using docker compose (I think it's very easy to convert the mounts into raw docker run command)
```
...
volumes:
    - /var/run/docker.sock:/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /sys:/sys:ro
    - /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
    - /lib/x86_64-linux-gnu/libcgmanager.so.0:/lib/x86_64-linux-gnu/libcgmanager.so.0
    - /lib/x86_64-linux-gnu/libnih.so.1:/lib/x86_64-linux-gnu/libnih.so.1
    - /lib/x86_64-linux-gnu/libnih-dbus.so.1:/lib/x86_64-linux-gnu/libnih-dbus.so.1
    - /lib/x86_64-linux-gnu/libgcrypt.so.11:/lib/x86_64-linux-gnu/libgcrypt.so.11
```

My Env:
$ cat /proc/version
Linux version 3.16.0-30-generic (buildd@kissel) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
$ docker -v
Docker version 1.11.0, build 4dc5990
$ docker-compose -v
docker-compose version 1.6.2, build 4d72027

Hope it helps.

**Comment by asridharan** [comment]
I think the problem here seems to be that bind mounting the docker.sock is not enough, you need to bind mount the docker client binary as well. However this is fraught with errors since latest versions of docker client are not purely static go binaries, and have dependencies on other shared objects.

The right solution (discussed and proposed by @jieyu ) seems to be to build the Mesos docker containers using the docker in docker build file , but replacing the base image with Ubuntu 14.04 instead of Alpine linux. The resulting image should have the docker client packaged correctly with the Mesos binaries. The Mesos docker container should be able to launch docker containers using the host docker daemon.
