### ISSUE TITLE
Image for mesos 0.24.1

### ISSUE THREAD

**Issue by gregory90** [mesosphere/docker-containers#26]
There's no image for mesos 0.24.1. It'd be cool if there was one:)
Thanks in advance!

**Comment by ssk2** [comment]
Hey @gregory90, @artemharutyunyan is working on this! Sorry for the delay, we're working on improving the Mesos packaging and release process, so this should be more seamless in the future.

**Comment by ssk2** [comment]
Looks like they're up now! Let us know if you have any issues.
