### ISSUE TITLE
Chronos Image for Mesos 0.25

### ISSUE THREAD

**Issue by cmfatih** [mesosphere/docker-containers#34]
Any chance to get a Docker image for Mesos 0.25?

**Comment by ssk2** [comment]
Hi @cmfatih - I think there is one - 0.25.0-0.2.70.ubuntu1404. Does this help or are you looking for some thing different?

**Comment by cmfatih** [comment]
@ssk2 : Hi, I don't see it at https://hub.docker.com/r/mesosphere/chronos/tags/

**Comment by ssk2** [comment]
Ah, okay! I'll get that built.

**Comment by cmfatih** [comment]
thanks :+1:

**Comment by ssk2** [comment]
@cmfatih - I just pushed `chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.25.0-0.2.70.ubuntu1404`. Let me know if you run into any issues!

**Comment by cmfatih** [comment]
@ssk2 : thanks! :smile:
