### ISSUE TITLE
mesoscloud Docker images outdated and misconfigured

### ISSUE THREAD

**Issue by marekzawadzki** [mesosphere/docker-containers#37]
Mesoscloud docker files (https://github.com/mesoscloud) don't include the newest versions of:

- Marathon (the newest is 0.13.0, mesoscloud maintains 0.11.0)
- Mesos (the newest is 0.26.0, mesoscloud maintains 0.24.1)

There are also some disadvantages of the mesoscloud images:

- ZooKeeper is installed from some tarball, while it can be easily
installed from Mesosphere package repository like the other components
- all containers are running as root - there is no need for that except
mesos-slave repo and IMO it's a good practice to run applications as
non-root user if possible

**Comment by adam-mesos** [comment]
This is the repo for the Mesosphere images. Mesoscloud issues should be filed at the mesoscloud repo. Looks like they already have PRs for Mesos 0.26 and Marathon 0.13
https://github.com/mesoscloud/mesos-master/pull/3
https://github.com/mesoscloud/mesos-slave/pull/3
https://github.com/mesoscloud/marathon/pull/2

We can try to address the ZK and root-user issues here though.

**Comment by asridharan** [comment]
This looks more of a mesoscloud issue rather than anything to do with the Mesosphere images. Had a discussion with @adam-mesos and we decided to close this issue, based on the fact that this needs to be fixed in the mesoscloud repo.
